/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Clock.h>
#include <RTX51.h>
#include <Clk_PWM.h>
#include <PWM_Out.h>
#include <PWM_Out_aliases.h>
#include <PWM.h>
#include <K2_SENSE.h>
#include <K2_SENSE_aliases.h>
#include <K1_SENSE.h>
#include <K1_SENSE_aliases.h>
#include <EMISO.h>
#include <EMISO_aliases.h>
#include <ECS.h>
#include <ECS_aliases.h>
#include <ECLK.h>
#include <ECLK_aliases.h>
#include <EMOSI.h>
#include <EMOSI_aliases.h>
#include <SPIS.h>
#include <SPIS_PVT.h>
#include <DEC_INT.h>
#include <DEC_INT_aliases.h>
#include <isr_QD.h>
#include <Clock_QD.h>
#include <EN_SW1.h>
#include <EN_SW1_aliases.h>
#include <EN_CHB.h>
#include <EN_CHB_aliases.h>
#include <EN_CHA.h>
#include <EN_CHA_aliases.h>
#include <QuadDecoder.h>
#include <Key2_2.h>
#include <Key2_2_aliases.h>
#include <Key2_1.h>
#include <Key2_1_aliases.h>
#include <Key2_0.h>
#include <Key2_0_aliases.h>
#include <Key1_1.h>
#include <Key1_1_aliases.h>
#include <KEY.h>
#include <KEY_aliases.h>
#include <MOSI.h>
#include <MOSI_aliases.h>
#include <MISO.h>
#include <MISO_aliases.h>
#include <k_isr.h>
#include <PSoC_INT1.h>
#include <PSoC_INT1_aliases.h>
#include <Key1_0.h>
#include <Key1_0_aliases.h>
#include <PSoC_INT0.h>
#include <PSoC_INT0_aliases.h>
#include <SPIM.h>
#include <SPIM_PVT.h>
#include <SCK.h>
#include <SCK_aliases.h>
#include <CSN.h>
#include <CSN_aliases.h>
#include <isr.h>
#include <Key1_2.h>
#include <Key1_2_aliases.h>
#include <UART.h>
#include <U_CLOCK.h>
#include <PC_VI_2SEL0.h>
#include <PC_VI_2SEL0_aliases.h>
#include <BICM_SEL.h>
#include <BICM_SEL_aliases.h>
#include <BFG1_SEL.h>
#include <BFG1_SEL_aliases.h>
#include <MUXASEL.h>
#include <MUXASEL_aliases.h>
#include <SRC_0.h>
#include <SRC_0_aliases.h>
#include <SRC_1.h>
#include <SRC_1_aliases.h>
#include <SRC_2.h>
#include <SRC_2_aliases.h>
#include <SRC_3.h>
#include <SRC_3_aliases.h>
#include <SRC_4.h>
#include <SRC_4_aliases.h>
#include <PC_VI_2SEL1.h>
#include <PC_VI_2SEL1_aliases.h>
#include <GPIO0_5V.h>
#include <GPIO0_5V_aliases.h>
#include <BSRC_IMP_SEL.h>
#include <BSRC_IMP_SEL_aliases.h>
#include <GPIO5.h>
#include <GPIO5_aliases.h>
#include <MUXSEL_B0.h>
#include <MUXSEL_B0_aliases.h>
#include <MUXSEL_B1.h>
#include <MUXSEL_B1_aliases.h>
#include <SPIS_IntClock.h>
#include <QuadDecoder_Cnt8.h>
#include <SPIM_IntClock.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/

