# -------------------------------------------------
# Project created by QtCreator 2014-05-28T15:17:05
# -------------------------------------------------
TARGET = test_PSOCInterface2
TEMPLATE = app
SOURCES += ../../PortableTester/QDigitalClock.cpp \
    ../../PortableTester/colors.cpp \
    ../../PortableTester/main.cpp \
    ../../PortableTester/mainwindowview.cpp \
    ../../PortableTester/portabletester.cpp \
    ../../PortableTester/probestatus.cpp \
    ../../PortableTester/qmaxbutton.cpp \
    ../../VINew/EffectLabel.cpp \
    ../../VINew/ad5293.cpp \
    ../../VINew/ad5318components.cpp \
    ../../VINew/autocurvefittraces.cpp \
    ../../VINew/clipdialog.cpp \
    ../../VINew/colors.cpp \
    ../../VINew/embeddedkeys.cpp \
    ../../VINew/main.cpp \
    ../../VINew/mainwindow.cpp \
    ../../VINew/multipletraces.cpp \
    ../../VINew/mutlipewavedialog.cpp \
    ../../VINew/plotter.cpp \
    ../../VINew/ptviinterface.cpp \
    ../../VINew/qmaxbutton.cpp \
    ../../VINew/selectprobe.cpp \
    ../../VINew/vidataclas.cpp \
    ../../VINew/vifunctionallogic.cpp \
    ../../VINew/vihwclass.cpp \
    ../../VINew/vimodelview.cpp \
    ../../VINew/visettings.cpp \
    ../../FGNew/ad5293.cpp \
    ../../FGNew/ad5318components.cpp \
    ../../FGNew/colors.cpp \
    ../../FGNew/fg.cpp \
    ../../FGNew/fgmodel.cpp \
    ../../FGNew/hardwareinterface.cpp \
    ../../FGNew/main.cpp \
    ../../FGNew/plotter.cpp \
    ../../FGNew/ptfginterface.cpp \
    ../../SLControl/offset.cpp \
    ../../SLControl/ptslinterface.cpp \
    ../../SLControl/shortlocater.cpp \
    ../../SLControl/slcontrol.cpp \
    ../../ICMUIInterface/ad5293.cpp \
    ../../ICMUIInterface/ad5318components.cpp \
    ../../ICMUIInterface/ad7190component.cpp \
    ../../ICMUIInterface/daccalibration.cpp \
    ../../ICMUIInterface/icm.cpp \
    ../../ICMUIInterface/main.cpp \
    ../../ICMUIInterface/pticminterface.cpp \
    ../../ICMUIInterface/settings.cpp \
    ../../Calibration/HY3131CalibInterface/hy3131calibinterface.cpp \
    ../../Calibration/HY3131CalibInterface/hy3131calibration.cpp \
    ../../Calibration/ReferenceCalibration/IRefCALIBWidget.cpp \
    ../../Calibration/ReferenceCalibration/ad5293.cpp \
    ../../Calibration/ReferenceCalibration/ad5318components.cpp \
    ../../Calibration/ReferenceCalibration/daccalibration.cpp \
    ../../Calibration/ReferenceCalibration/main.cpp \
    ../../Calibration/GCalibration/IGCALIBWidget.cpp \
    ../../Calibration/GCalibration/daccalibration.cpp \
    ../../Calibration/GCalibration/main.cpp \
    ../../Calibration/CalibrationInterface/calibrationinterface.cpp \
    ../../CalibReport/CalibReport.cpp \
    ../../Calibration/ICalibration/IICALIBWidget.cpp \
    ../../Calibration/ICalibration/ad5318components.cpp \
    ../../Calibration/ICalibration/daccalibration.cpp \
    ../../Calibration/ICalibration/main.cpp \
    ../../DMM/DMMAccuracy/dmmaccuracy.cpp \
    ../../DMM/DMMAccuracy/main.cpp \
    ../../DMM/HY3131CalibInterface/hy3131calibinterface.cpp \
    ../../DMM/HY3131CalibInterface/hy3131calibration.cpp \
    ../../Testjig/PortableTesterTestJig2/documentwidget.cpp \
    ../../Testjig/PortableTesterTestJig2/main.cpp \
    ../../Testjig/PortableTesterTestJig2/portabletestertestjig2.cpp \
    ../../Testjig/PTPSoCTestJigInterface2/IPSoCWidget.cpp \
    ../../Testjig/PTPSoCTestJigInterface2/main.cpp \
    ../../Testjig/PTPSoCTestJigInterface2/ptpsoctestjiginterface2.cpp \
    ../../Testjig/AD9102GUI/AD9102.cpp \
    ../../Testjig/AD9102GUI/IAD9102Widget.cpp \
    ../../Testjig/AD9102GUI/ad9102ui.cpp \
    ../../Testjig/AD9102GUI/main.cpp \
    ../../Testjig/FLASHMEMORY/IFMWidget.cpp \
    ../../Testjig/FLASHMEMORY/flashMemory.cpp \
    ../../Testjig/FLASHMEMORY/main.cpp \
    ../../Testjig/FLASHMEMORY/messagewidget.cpp \
    ../../Testjig/ADCHighAccuracy/IHACADCWidget.cpp \
    ../../Testjig/ADCHighAccuracy/ad5318components.cpp \
    ../../Testjig/ADCHighAccuracy/ad7190component.cpp \
    ../../Testjig/ADCHighAccuracy/adhighaccuracy.cpp \
    ../../Testjig/ADCHighAccuracy/main.cpp \
    ../../Testjig/APPCardDRVRECE/IAPPRXDRVWidget.cpp \
    ../../Testjig/APPCardDRVRECE/main.cpp \
    ../../Testjig/APPCardDRVRECE/ptappcarddrvrecev.cpp \
    ../../Testjig/APPCardRelayUI/IACRWidget.cpp \
    ../../Testjig/APPCardRelayUI/ICMJig/IICMWidget.cpp \
    ../../Testjig/APPCardRelayUI/ICMJig/ad5318components.cpp \
    ../../Testjig/APPCardRelayUI/ICMJig/ad7190component.cpp \
    ../../Testjig/APPCardRelayUI/ICMJig/main.cpp \
    ../../Testjig/APPCardRelayUI/ICMJig/widget.cpp \
    ../../Testjig/APPCardRelayUI/appcardrelayread.cpp \
    ../../Testjig/APPCardRelayUI/main.cpp \
    ../../Testjig/APPCardRelayUI/mainwindow.cpp \
    ../../Testjig/AWG/IAWGWidget.cpp \
    ../../Testjig/AWG/main.cpp \
    ../../Testjig/AWG/widget.cpp \
    ../../Testjig/DDS/IDDSWidget.cpp \
    ../../Testjig/DDS/ad5293.cpp \
    ../../Testjig/DDS/ad5318components.cpp \
    ../../Testjig/DDS/daccalibration.cpp \
    ../../Testjig/DDS/ddswidget.cpp \
    ../../Testjig/DDS/main.cpp \
    ../../Testjig/DMM/IDMMWidget.cpp \
    ../../Testjig/DMM/ad5318components.cpp \
    ../../Testjig/DMM/ad7190component.cpp \
    ../../Testjig/DMM/dmmjig.cpp \
    ../../Testjig/DMM/main.cpp \
    ../../Testjig/ICMJig/IICMWidget.cpp \
    ../../Testjig/ICMJig/ad5318components.cpp \
    ../../Testjig/ICMJig/ad7190component.cpp \
    ../../Testjig/ICMJig/main.cpp \
    ../../Testjig/ICMJig/widget.cpp \
    ../../Testjig/PlotWaveForm/IPWFWidget.cpp \
    ../../Testjig/PlotWaveForm/main.cpp \
    ../../Testjig/PlotWaveForm/plotter.cpp \
    ../../Testjig/PlotWaveForm/widget.cpp \
    ../../Testjig/PtKeyKnob/IKeyKnobWidget.cpp \
    ../../Testjig/PtKeyKnob/main.cpp \
    ../../Testjig/PtKeyKnob/ptkeyknob.cpp \
    ../../Testjig/PTMuxTestjig/ad5318components.cpp \
    ../../Testjig/PTMuxTestjig/main.cpp \
    ../../Testjig/PTMuxTestjig/muxjig.cpp \
    ../../Testjig/RAMData/IRAMWidget.cpp \
    ../../Testjig/RAMData/main.cpp \
    ../../Testjig/RAMData/widget.cpp \
    ../../Testjig/VI/IVIWidget.cpp \
    ../../Testjig/VI/main.cpp \
    ../../Testjig/VI/vijig.cpp \
    ../../Testjig/ADCHighSpeed/adchighspeed.cpp \
    ../../Testjig/ADCHighSpeed/isla118p50component.cpp \
    ../../Testjig/ADCHighSpeed/main.cpp \
    ../../Testjig/AD5318/IAD5318Widget.cpp \
    ../../Testjig/AD5318/ad5293.cpp \
    ../../Testjig/AD5318/ad5318.cpp \
    ../../Testjig/AD5318/ad5318components.cpp \
    ../../Testjig/AD5318/ad7190component.cpp \
    ../../Testjig/AD5318/main.cpp \
    ../../Testjig/PTAppBckPsoc/IPTAppBckPsocWidget.cpp \
    ../../Testjig/PTAppBckPsoc/main.cpp \
    ../../Testjig/PTAppBckPsoc/ptpsoctestjiginterface.cpp \
    ../../DMM/Keithley2100Lib/keithley2100lib.cpp \
    ../../BackPlaneInterface/ibackplane.cpp \
    ../../PTApplicationcardInterface/ptapplicationcardplugin.cpp \
    ../../SPIMemoryInterface/spimemoryinterface.cpp \
    ../../PTPsocInterface2/ptpsocinterface2.cpp \
    ../../PTPsocInterface2/src/qextserialenumerator.cpp \
    ../../PTPsocInterface2/src/qextserialenumerator_linux.cpp \
    ../../PTPsocInterface2/src/qextserialenumerator_osx.cpp \
    ../../PTPsocInterface2/src/qextserialenumerator_unix.cpp \
    ../../PTPsocInterface2/src/qextserialenumerator_win.cpp \
    ../../PTPsocInterface2/src/qextserialport.cpp \
    ../../PTPsocInterface2/src/qextserialport_unix.cpp \
    ../../PTPsocInterface2/src/qextserialport_win.cpp \
    ../../PTComponentsInterface/ptcomponentsinterface.cpp \
    ../../QmaxPTInterface/colors.cpp \
    ../../QmaxPTInterface/displayinfo.cpp \
    ../../QmaxPTInterface/myLineEdit.cpp \
    ../../QmaxPTInterface/myinputpanel.cpp \
    ../../QmaxPTInterface/numberpanel.cpp \
    ../../QmaxPTInterface/qmaxbutton.cpp \
    ../../QmaxPTInterface/qmaxmessagebox.cpp \
    ../../QmaxPTInterface/qmaxptinterface.cpp \
    ../../QmaxPTInterface/qmaxptlibrary.cpp \
    ../../QmaxPTInterface/widget.cpp \
    ../../PTGPIOPinInterface/ptgpiopininterface.cpp \
    ../../GPIOEventInterface/gpioeventinterface.cpp \
    ../../PTKeyEventInterfaces/KeyObject.cpp \
    ../../PTKeyEventInterfaces/PTKeyEventInterface.cpp \
    ../../PTSplashInterface/interfacewrapper.cpp \
    ../../PTSplashInterface/ptsplashinterface.cpp \
    ../../Keithley2100Lib/keithley2100lib.cpp \
    ../../PTDMMLibInterface/ad5318components.cpp \
    ../../PTDMMLibInterface/ad7190component.cpp \
    ../../PTDMMLibInterface/ptdmmlibinterface.cpp \
    ../../DMM/HY3131DMMLib/hy3131dmmlib.cpp \
    ../../Calibration/OpenShortCalib/ad5293.cpp \
    ../../Calibration/OpenShortCalib/ad5318components.cpp \
    ../../Calibration/OpenShortCalib/ad7190component.cpp \
    ../../Calibration/OpenShortCalib/main.cpp \
    ../../Calibration/OpenShortCalib/openshortcalib.cpp \
    ../../Calibration/RXCalibration/IRXCALIBWidget.cpp \
    ../../Calibration/RXCalibration/ad5293.cpp \
    ../../Calibration/RXCalibration/ad5318components.cpp \
    ../../Calibration/RXCalibration/ad7190component.cpp \
    ../../Calibration/RXCalibration/adccalibration.cpp \
    ../../Calibration/RXCalibration/main.cpp \
    ../../SPIController/AD5260.cpp \
    ../../SPIController/AD5293.cpp \
    ../../SPIController/AD5318.cpp \
    ../../SPIController/DAC8563.cpp \
    ../../SPIController/DSOPSOC.cpp \
    ../../SPIController/ISLA118P50.cpp \
    ../../SPIController/LMH6518.cpp \
    ../../SPIController/spicontroller.cpp \
    ../test_Buzzer/main.cpp \
    ../test_Buzzer/mainwindow.cpp \
    ../testSPI/DMMSPIWidget.cpp \
    ../testSPI/hy3131calibration.cpp \
    ../testSPI/main.cpp \
    ../testSPI/testspi.cpp \
    ../testKeithley2100Lib/main.cpp \
    ../testKeithley2100Lib/testkeithley2100lib.cpp \
    ../test_Encoder_SPI/main.cpp \
    ../test_Encoder_SPI/testencoder.cpp \
    ../TestMuxStatus/main.cpp \
    ../TestMuxStatus/mainwindow.cpp \
    ../../Calibration/VCalibration/IVCALIBWidget.cpp \
    ../../Calibration/VCalibration/ad5293.cpp \
    ../../Calibration/VCalibration/ad5318components.cpp \
    ../../Calibration/VCalibration/daccalibration.cpp \
    ../../Calibration/VCalibration/main.cpp \
    ../../Calibration/VICalibration/IVCALIBWidget.cpp \
    ../../Calibration/VICalibration/ad5293.cpp \
    ../../Calibration/VICalibration/ad5318components.cpp \
    ../../Calibration/VICalibration/daccalibration.cpp \
    ../../Calibration/VICalibration/main.cpp \
    ../testADCHighSpeed/main.cpp \
    ../testADCHighSpeed/mainwindow.cpp \
    ../testHY3131CalibInterface/main.cpp \
    ../testHY3131CalibInterface/mainwindow.cpp \
    ../test_calibReportInterface/main.cpp \
    ../test_calibReportInterface/test_calibreportinterface.cpp \
    ../test_HY3131DMMLib/main.cpp \
    ../test_HY3131DMMLib/mainwindow.cpp \
    main.cpp \
    testpsocinterface2.cpp \
    main.cpp \
    testpsocinterface2.cpp
HEADERS += ../../PortableTester/AppdeviceRegisterDetails.h \
    ../../PortableTester/ApplicationCardInterface.h \
    ../../PortableTester/BackPlaneInterface.h \
    ../../PortableTester/GPIOInterfaces.h \
    ../../PortableTester/IHWIDInterface.h \
    ../../PortableTester/IPSOCCommunication.h \
    ../../PortableTester/InterfacePTLibrary.h \
    ../../PortableTester/PTEventInterfaces.h \
    ../../PortableTester/PTGPIOEventInterfaces.h \
    ../../PortableTester/QDigitalClock.h \
    ../../PortableTester/StdAPI.h \
    ../../PortableTester/UtilityWidgetInterface.h \
    ../../PortableTester/appcardfunctiontemplate.h \
    ../../PortableTester/colors.h \
    ../../PortableTester/mainwindowview.h \
    ../../PortableTester/operatorInterface.h \
    ../../PortableTester/portabletester.h \
    ../../PortableTester/probestatus.h \
    ../../PortableTester/qmaxbutton.h \
    ../../PortableTester/serialdevice.h \
    ../../VINew/AppdeviceRegisterDetails.h \
    ../../VINew/ApplicationCardInterface.h \
    ../../VINew/BackPlaneInterface.h \
    ../../VINew/CalibrationInterfaces.h \
    ../../VINew/EffectLabel.h \
    ../../VINew/GPIOInterfaces.h \
    ../../VINew/IPSOCCommunication.h \
    ../../VINew/InterfaceFunctionalComponents.h \
    ../../VINew/InterfacePTLibrary.h \
    ../../VINew/PTEventInterfaces.h \
    ../../VINew/PTGPIOEventInterfaces.h \
    ../../VINew/PTSPIMemoryInterface.h \
    ../../VINew/PTSplashScreen.h \
    ../../VINew/RLCInterface.h \
    ../../VINew/Waveformclass.h \
    ../../VINew/ad5293.h \
    ../../VINew/ad5318components.h \
    ../../VINew/appcardcomponents.h \
    ../../VINew/appcardfunctiontemplate.h \
    ../../VINew/autocurvefittraces.h \
    ../../VINew/clipdialog.h \
    ../../VINew/colors.h \
    ../../VINew/embeddedkeys.h \
    ../../VINew/interfaceHeader.h \
    ../../VINew/mainwindow.h \
    ../../VINew/multipletraces.h \
    ../../VINew/mutlipewavedialog.h \
    ../../VINew/plotter.h \
    ../../VINew/ptviinterface.h \
    ../../VINew/qmaxbutton.h \
    ../../VINew/qtsvgpixmapcache.h \
    ../../VINew/qtsvgslideswitch.h \
    ../../VINew/selectprobe.h \
    ../../VINew/serialdevice.h \
    ../../VINew/vidataclas.h \
    ../../VINew/vifunctionallogic.h \
    ../../VINew/vihwclass.h \
    ../../VINew/vimodelview.h \
    ../../VINew/visettings.h \
    ../../FGNew/AppdeviceRegisterDetails.h \
    ../../FGNew/ApplicationCardInterface.h \
    ../../FGNew/BackPlaneInterface.h \
    ../../FGNew/CalibrationInterfaces.h \
    ../../FGNew/FGMacros.h \
    ../../FGNew/GPIOInterfaces.h \
    ../../FGNew/IPSOCCommunication.h \
    ../../FGNew/InterfaceFunctionalComponents.h \
    ../../FGNew/InterfacePTLibrary.h \
    ../../FGNew/PTAppBckPsocInterface.h \
    ../../FGNew/PTEventInterfaces.h \
    ../../FGNew/PTGPIOEventInterfaces.h \
    ../../FGNew/PTSPIMemoryInterface.h \
    ../../FGNew/RefCALIBTestJigInterface.h \
    ../../FGNew/Waveformclass.h \
    ../../FGNew/ad5293.h \
    ../../FGNew/ad5318components.h \
    ../../FGNew/appcardcomponents.h \
    ../../FGNew/appcardfunctiontemplate.h \
    ../../FGNew/colors.h \
    ../../FGNew/fg.h \
    ../../FGNew/fgmodel.h \
    ../../FGNew/hardwareinterface.h \
    ../../FGNew/interfaceHeader.h \
    ../../FGNew/plotter.h \
    ../../FGNew/ptfginterface.h \
    ../../FGNew/serialdevice.h \
    ../../SLControl/AppdeviceRegisterDetails.h \
    ../../SLControl/ApplicationCardInterface.h \
    ../../SLControl/BackPlaneInterface.h \
    ../../SLControl/DMMLibInterface.h \
    ../../SLControl/GPIOInterfaces.h \
    ../../SLControl/HACADCTestJigInterface.h \
    ../../SLControl/IPSOCCommunication.h \
    ../../SLControl/InterfacePTLibrary.h \
    ../../SLControl/PTAppBckPsocInterface.h \
    ../../SLControl/PTEventInterfaces.h \
    ../../SLControl/PTGPIOEventInterfaces.h \
    ../../SLControl/SLControl_global.h \
    ../../SLControl/appcardfunctiontemplate.h \
    ../../SLControl/display.h \
    ../../SLControl/interfaceHeader.h \
    ../../SLControl/offset.h \
    ../../SLControl/ptslinterface.h \
    ../../SLControl/serialdevice.h \
    ../../SLControl/shortlocater.h \
    ../../SLControl/slcontrol.h \
    ../../ICMUIInterface/AppdeviceRegisterDetails.h \
    ../../ICMUIInterface/ApplicationCardInterface.h \
    ../../ICMUIInterface/BackPlaneInterface.h \
    ../../ICMUIInterface/GCALIBTestJigInterface.h \
    ../../ICMUIInterface/GPIOInterfaces.h \
    ../../ICMUIInterface/IPSOCCommunication.h \
    ../../ICMUIInterface/InterfaceFunctionalComponents.h \
    ../../ICMUIInterface/InterfacePTLibrary.h \
    ../../ICMUIInterface/PTAppBckPsocInterface.h \
    ../../ICMUIInterface/PTEventInterfaces.h \
    ../../ICMUIInterface/PTGPIOEventInterfaces.h \
    ../../ICMUIInterface/PTLibraryInterfaces.h \
    ../../ICMUIInterface/PTSPIMemoryInterface.h \
    ../../ICMUIInterface/ad5293.h \
    ../../ICMUIInterface/ad5318components.h \
    ../../ICMUIInterface/ad7190component.h \
    ../../ICMUIInterface/appcardcomponents.h \
    ../../ICMUIInterface/appcardfunctiontemplate.h \
    ../../ICMUIInterface/daccalibration.h \
    ../../ICMUIInterface/display.h \
    ../../ICMUIInterface/hardwareinterface.h \
    ../../ICMUIInterface/icm.h \
    ../../ICMUIInterface/interfaceHeader.h \
    ../../ICMUIInterface/pticminterface.h \
    ../../ICMUIInterface/serialdevice.h \
    ../../ICMUIInterface/settings.h \
    ../../Calibration/HY3131CalibInterface/AppdeviceRegisterDetails.h \
    ../../Calibration/HY3131CalibInterface/ApplicationCardInterface.h \
    ../../Calibration/HY3131CalibInterface/HY3131Calib.h \
    ../../Calibration/HY3131CalibInterface/HY3131DMMLibInterface.h \
    ../../Calibration/HY3131CalibInterface/HY3131Macro.h \
    ../../Calibration/HY3131CalibInterface/InterfaceFunctionalComponents.h \
    ../../Calibration/HY3131CalibInterface/InterfacePTLibrary.h \
    ../../Calibration/HY3131CalibInterface/Keithley2100Interface.h \
    ../../Calibration/HY3131CalibInterface/appcardcomponents.h \
    ../../Calibration/HY3131CalibInterface/appcardfunctiontemplate.h \
    ../../Calibration/HY3131CalibInterface/hy3131calibinterface.h \
    ../../Calibration/HY3131CalibInterface/hy3131calibration.h \
    ../../Calibration/ReferenceCalibration/AppdeviceRegisterDetails.h \
    ../../Calibration/ReferenceCalibration/ApplicationCardInterface.h \
    ../../Calibration/ReferenceCalibration/IRefCALIBWidget.h \
    ../../Calibration/ReferenceCalibration/InterfaceFunctionalComponents.h \
    ../../Calibration/ReferenceCalibration/PTLibraryInterfaces.h \
    ../../Calibration/ReferenceCalibration/RefCALIBTestJigInterface.h \
    ../../Calibration/ReferenceCalibration/ad5293.h \
    ../../Calibration/ReferenceCalibration/ad5318components.h \
    ../../Calibration/ReferenceCalibration/appcardcomponents.h \
    ../../Calibration/ReferenceCalibration/appcardfunctiontemplate.h \
    ../../Calibration/ReferenceCalibration/daccalibration.h \
    ../../Calibration/GCalibration/GCALIBTestJigInterface.h \
    ../../Calibration/GCalibration/IGCALIBWidget.h \
    ../../Calibration/GCalibration/InterfaceFunctionalComponents.h \
    ../../Calibration/GCalibration/PTLibraryInterfaces.h \
    ../../Calibration/GCalibration/ad5318components.h \
    ../../Calibration/GCalibration/daccalibration.h \
    ../../Calibration/CalibrationInterface/CalibrationInterfaces.h \
    ../../Calibration/CalibrationInterface/calibrationinterface.h \
    ../../CalibReport/CalibReport.h \
    ../../CalibReport/CalibReportInterface.h \
    ../../Calibration/ICalibration/AppdeviceRegisterDetails.h \
    ../../Calibration/ICalibration/ApplicationCardInterface.h \
    ../../Calibration/ICalibration/ICALIBTestJigInterface.h \
    ../../Calibration/ICalibration/IICALIBWidget.h \
    ../../Calibration/ICalibration/InterfaceFunctionalComponents.h \
    ../../Calibration/ICalibration/PTLibraryInterfaces.h \
    ../../Calibration/ICalibration/ad5318components.h \
    ../../Calibration/ICalibration/appcardcomponents.h \
    ../../Calibration/ICalibration/appcardfunctiontemplate.h \
    ../../Calibration/ICalibration/daccalibration.h \
    ../../DMM/DMMAccuracy/dmmaccuracy.h \
    ../../DMM/HY3131CalibInterface/AppdeviceRegisterDetails.h \
    ../../DMM/HY3131CalibInterface/ApplicationCardInterface.h \
    ../../DMM/HY3131CalibInterface/HY3131Calib.h \
    ../../DMM/HY3131CalibInterface/HY3131DMMLibInterface.h \
    ../../DMM/HY3131CalibInterface/HY3131Macro.h \
    ../../DMM/HY3131CalibInterface/InterfaceFunctionalComponents.h \
    ../../DMM/HY3131CalibInterface/InterfacePTLibrary.h \
    ../../DMM/HY3131CalibInterface/Keithley2100Interface.h \
    ../../DMM/HY3131CalibInterface/appcardcomponents.h \
    ../../DMM/HY3131CalibInterface/appcardfunctiontemplate.h \
    ../../DMM/HY3131CalibInterface/hy3131calibinterface.h \
    ../../DMM/HY3131CalibInterface/hy3131calibration.h \
    ../../Testjig/PortableTesterTestJig2/ACRTestJigInterface.h \
    ../../Testjig/PortableTesterTestJig2/AD5318TestJigInterface.h \
    ../../Testjig/PortableTesterTestJig2/AD9102TestJigInterface.h \
    ../../Testjig/PortableTesterTestJig2/APPRXDRVTestJigInterface.h \
    ../../Testjig/PortableTesterTestJig2/AWGTestJigInterface.h \
    ../../Testjig/PortableTesterTestJig2/AppdeviceRegisterDetails.h \
    ../../Testjig/PortableTesterTestJig2/ApplicationCardInterface.h \
    ../../Testjig/PortableTesterTestJig2/DDSTestJigInterface.h \
    ../../Testjig/PortableTesterTestJig2/DMMTestJigInterface.h \
    ../../Testjig/PortableTesterTestJig2/FMTestJigInterface.h \
    ../../Testjig/PortableTesterTestJig2/HACADCTestJigInterface.h \
    ../../Testjig/PortableTesterTestJig2/ICMTestJigInterface.h \
    ../../Testjig/PortableTesterTestJig2/IPSOCCommunication.h \
    ../../Testjig/PortableTesterTestJig2/InterfacePTLibrary.h \
    ../../Testjig/PortableTesterTestJig2/KeyKnobTestJigInterface.h \
    ../../Testjig/PortableTesterTestJig2/PSoCTestJigInterface.h \
    ../../Testjig/PortableTesterTestJig2/PSoCTestJigInterface2.h \
    ../../Testjig/PortableTesterTestJig2/PWFTestJigInterface.h \
    ../../Testjig/PortableTesterTestJig2/RAMTestJigInterface.h \
    ../../Testjig/PortableTesterTestJig2/VITestJigInterface.h \
    ../../Testjig/PortableTesterTestJig2/ViewerTestJigInterface.h \
    ../../Testjig/PortableTesterTestJig2/appcardfunctiontemplate.h \
    ../../Testjig/PortableTesterTestJig2/documentwidget.h \
    ../../Testjig/PortableTesterTestJig2/poppler-annotation-helper.h \
    ../../Testjig/PortableTesterTestJig2/poppler-annotation-private.h \
    ../../Testjig/PortableTesterTestJig2/poppler-annotation.h \
    ../../Testjig/PortableTesterTestJig2/poppler-converter-private.h \
    ../../Testjig/PortableTesterTestJig2/poppler-embeddedfile-private.h \
    ../../Testjig/PortableTesterTestJig2/poppler-export.h \
    ../../Testjig/PortableTesterTestJig2/poppler-form.h \
    ../../Testjig/PortableTesterTestJig2/poppler-link-extractor-private.h \
    ../../Testjig/PortableTesterTestJig2/poppler-link.h \
    ../../Testjig/PortableTesterTestJig2/poppler-media.h \
    ../../Testjig/PortableTesterTestJig2/poppler-optcontent-private.h \
    ../../Testjig/PortableTesterTestJig2/poppler-optcontent.h \
    ../../Testjig/PortableTesterTestJig2/poppler-page-private.h \
    ../../Testjig/PortableTesterTestJig2/poppler-page-transition-private.h \
    ../../Testjig/PortableTesterTestJig2/poppler-page-transition.h \
    ../../Testjig/PortableTesterTestJig2/poppler-private.h \
    ../../Testjig/PortableTesterTestJig2/poppler-qiodeviceoutstream-private.h \
    ../../Testjig/PortableTesterTestJig2/poppler-qt4.h \
    ../../Testjig/PortableTesterTestJig2/portabletestertestjig2.h \
    ../../Testjig/PortableTesterTestJig2/serialdevice.h \
    ../../Testjig/PTPSoCTestJigInterface2/BackPlaneInterface.h \
    ../../Testjig/PTPSoCTestJigInterface2/GPIOInterfaces.h \
    ../../Testjig/PTPSoCTestJigInterface2/IPSOCCommunication.h \
    ../../Testjig/PTPSoCTestJigInterface2/IPSoCWidget.h \
    ../../Testjig/PTPSoCTestJigInterface2/InterfacePTLibrary.h \
    ../../Testjig/PTPSoCTestJigInterface2/PSoCTestJigInterface2.h \
    ../../Testjig/PTPSoCTestJigInterface2/PTEventInterfaces.h \
    ../../Testjig/PTPSoCTestJigInterface2/PTGPIOEventInterfaces.h \
    ../../Testjig/PTPSoCTestJigInterface2/headers.h \
    ../../Testjig/PTPSoCTestJigInterface2/macros.h \
    ../../Testjig/PTPSoCTestJigInterface2/ptpsoctestjiginterface2.h \
    ../../Testjig/PTPSoCTestJigInterface2/serialdevice.h \
    ../../Testjig/AD9102GUI/AD9102.h \
    ../../Testjig/AD9102GUI/AD9102TestJigInterface.h \
    ../../Testjig/AD9102GUI/AppdeviceRegisterDetails.h \
    ../../Testjig/AD9102GUI/ApplicationCardInterface.h \
    ../../Testjig/AD9102GUI/IAD9102Widget.h \
    ../../Testjig/AD9102GUI/InterfaceFunctionalComponents.h \
    ../../Testjig/AD9102GUI/InterfacePTLibrary.h \
    ../../Testjig/AD9102GUI/ad9102ui.h \
    ../../Testjig/AD9102GUI/appcardcomponents.h \
    ../../Testjig/AD9102GUI/appcardfunctiontemplate.h \
    ../../Testjig/FLASHMEMORY/AppdeviceRegisterDetails.h \
    ../../Testjig/FLASHMEMORY/ApplicationCardInterface.h \
    ../../Testjig/FLASHMEMORY/BackPlaneInterface.h \
    ../../Testjig/FLASHMEMORY/FMTestJigInterface.h \
    ../../Testjig/FLASHMEMORY/IFMWidget.h \
    ../../Testjig/FLASHMEMORY/InterfacePTLibrary.h \
    ../../Testjig/FLASHMEMORY/PTSPIMemoryInterface.h \
    ../../Testjig/FLASHMEMORY/PTSplashScreen.h \
    ../../Testjig/FLASHMEMORY/appcardfunctiontemplate.h \
    ../../Testjig/FLASHMEMORY/flashMemory.h \
    ../../Testjig/FLASHMEMORY/messagewidget.h \
    ../../Testjig/ADCHighAccuracy/AppdeviceRegisterDetails.h \
    ../../Testjig/ADCHighAccuracy/ApplicationCardInterface.h \
    ../../Testjig/ADCHighAccuracy/HACADCTestJigInterface.h \
    ../../Testjig/ADCHighAccuracy/IHACADCWidget.h \
    ../../Testjig/ADCHighAccuracy/InterfaceFunctionalComponents.h \
    ../../Testjig/ADCHighAccuracy/ad5318components.h \
    ../../Testjig/ADCHighAccuracy/ad7190component.h \
    ../../Testjig/ADCHighAccuracy/adhighaccuracy.h \
    ../../Testjig/ADCHighAccuracy/appcardcomponents.h \
    ../../Testjig/ADCHighAccuracy/appcardfunctiontemplate.h \
    ../../Testjig/APPCardDRVRECE/APPRXDRVTestJigInterface.h \
    ../../Testjig/APPCardDRVRECE/AppdeviceRegisterDetails.h \
    ../../Testjig/APPCardDRVRECE/ApplicationCardInterface.h \
    ../../Testjig/APPCardDRVRECE/BackPlaneInterface.h \
    ../../Testjig/APPCardDRVRECE/IAPPRXDRVWidget.h \
    ../../Testjig/APPCardDRVRECE/PTLibraryInterfaces.h \
    ../../Testjig/APPCardDRVRECE/appcardfunctiontemplate.h \
    ../../Testjig/APPCardDRVRECE/ptappcarddrvrecev.h \
    ../../Testjig/APPCardRelayUI/ACRTestJigInterface.h \
    ../../Testjig/APPCardRelayUI/AppdeviceRegisterDetails.h \
    ../../Testjig/APPCardRelayUI/ApplicationCardInterface.h \
    ../../Testjig/APPCardRelayUI/BackPlaneInterface.h \
    ../../Testjig/APPCardRelayUI/IACRWidget.h \
    ../../Testjig/APPCardRelayUI/ICMJig/AppdeviceRegisterDetails.h \
    ../../Testjig/APPCardRelayUI/ICMJig/ApplicationCardInterface.h \
    ../../Testjig/APPCardRelayUI/ICMJig/ICMTestJigInterface.h \
    ../../Testjig/APPCardRelayUI/ICMJig/IICMWidget.h \
    ../../Testjig/APPCardRelayUI/ICMJig/InterfacePTLibrary.h \
    ../../Testjig/APPCardRelayUI/ICMJig/PTSPIMemoryInterface.h \
    ../../Testjig/APPCardRelayUI/ICMJig/WaveformTestjigInterface.h \
    ../../Testjig/APPCardRelayUI/ICMJig/ad5318components.h \
    ../../Testjig/APPCardRelayUI/ICMJig/ad7190component.h \
    ../../Testjig/APPCardRelayUI/ICMJig/appcardcomponents.h \
    ../../Testjig/APPCardRelayUI/ICMJig/appcardfunctiontemplate.h \
    ../../Testjig/APPCardRelayUI/ICMJig/widget.h \
    ../../Testjig/APPCardRelayUI/InterfacePTLibrary.h \
    ../../Testjig/APPCardRelayUI/appcardfunctiontemplate.h \
    ../../Testjig/APPCardRelayUI/appcardrelayread.h \
    ../../Testjig/APPCardRelayUI/mainwindow.h \
    ../../Testjig/AWG/AWGTestJigInterface.h \
    ../../Testjig/AWG/AppdeviceRegisterDetails.h \
    ../../Testjig/AWG/ApplicationCardInterface.h \
    ../../Testjig/AWG/IAWGWidget.h \
    ../../Testjig/AWG/InterfacePTLibrary.h \
    ../../Testjig/AWG/WaveformTestjigInterface.h \
    ../../Testjig/AWG/appcardfunctiontemplate.h \
    ../../Testjig/AWG/widget.h \
    ../../Testjig/DDS/AppdeviceRegisterDetails.h \
    ../../Testjig/DDS/ApplicationCardInterface.h \
    ../../Testjig/DDS/BackPlaneInterface.h \
    ../../Testjig/DDS/DDSTestJigInterface.h \
    ../../Testjig/DDS/IDDSWidget.h \
    ../../Testjig/DDS/InterfaceFunctionalComponents.h \
    ../../Testjig/DDS/PTGPIOEventInterfaces.h \
    ../../Testjig/DDS/PTLibraryInterfaces.h \
    ../../Testjig/DDS/ad5293.h \
    ../../Testjig/DDS/ad5318components.h \
    ../../Testjig/DDS/appcardcomponents.h \
    ../../Testjig/DDS/appcardfunctiontemplate.h \
    ../../Testjig/DDS/daccalibration.h \
    ../../Testjig/DDS/ddswidget.h \
    ../../Testjig/DMM/AppdeviceRegisterDetails.h \
    ../../Testjig/DMM/ApplicationCardInterface.h \
    ../../Testjig/DMM/DMMTestJigInterface.h \
    ../../Testjig/DMM/IDMMWidget.h \
    ../../Testjig/DMM/IPSOCCommunication.h \
    ../../Testjig/DMM/InterfaceFunctionalComponents.h \
    ../../Testjig/DMM/InterfacePTLibrary.h \
    ../../Testjig/DMM/WaveformTestjigInterface.h \
    ../../Testjig/DMM/ad5318components.h \
    ../../Testjig/DMM/ad7190component.h \
    ../../Testjig/DMM/appcardcomponents.h \
    ../../Testjig/DMM/appcardfunctiontemplate.h \
    ../../Testjig/DMM/dmmjig.h \
    ../../Testjig/ICMJig/AppdeviceRegisterDetails.h \
    ../../Testjig/ICMJig/ApplicationCardInterface.h \
    ../../Testjig/ICMJig/ICMTestJigInterface.h \
    ../../Testjig/ICMJig/IICMWidget.h \
    ../../Testjig/ICMJig/InterfacePTLibrary.h \
    ../../Testjig/ICMJig/PTSPIMemoryInterface.h \
    ../../Testjig/ICMJig/WaveformTestjigInterface.h \
    ../../Testjig/ICMJig/ad5318components.h \
    ../../Testjig/ICMJig/ad7190component.h \
    ../../Testjig/ICMJig/appcardcomponents.h \
    ../../Testjig/ICMJig/appcardfunctiontemplate.h \
    ../../Testjig/ICMJig/widget.h \
    ../../Testjig/PlotWaveForm/AppdeviceRegisterDetails.h \
    ../../Testjig/PlotWaveForm/ApplicationCardInterface.h \
    ../../Testjig/PlotWaveForm/IPWFWidget.h \
    ../../Testjig/PlotWaveForm/InterfacePTLibrary.h \
    ../../Testjig/PlotWaveForm/PTSPIMemoryInterface.h \
    ../../Testjig/PlotWaveForm/PWFTestJigInterface.h \
    ../../Testjig/PlotWaveForm/Waveformclass.h \
    ../../Testjig/PlotWaveForm/appcardfunctiontemplate.h \
    ../../Testjig/PlotWaveForm/plotter.h \
    ../../Testjig/PlotWaveForm/widget.h \
    ../../Testjig/PtKeyKnob/BackPlaneInterface.h \
    ../../Testjig/PtKeyKnob/IKeyKnobWidget.h \
    ../../Testjig/PtKeyKnob/KeyKnobTestJigInterface.h \
    ../../Testjig/PtKeyKnob/PTEventInterfaces.h \
    ../../Testjig/PtKeyKnob/PTGPIOEventInterfaces.h \
    ../../Testjig/PtKeyKnob/ptkeyknob.h \
    ../../Testjig/PTMuxTestjig/AppdeviceRegisterDetails.h \
    ../../Testjig/PTMuxTestjig/ApplicationCardInterface.h \
    ../../Testjig/PTMuxTestjig/BackPlaneInterface.h \
    ../../Testjig/PTMuxTestjig/IPSOCCommunication.h \
    ../../Testjig/PTMuxTestjig/InterfaceFunctionalComponents.h \
    ../../Testjig/PTMuxTestjig/PTAppBckPsocInterface.h \
    ../../Testjig/PTMuxTestjig/ad5318components.h \
    ../../Testjig/PTMuxTestjig/appcardcomponents.h \
    ../../Testjig/PTMuxTestjig/appcardfunctiontemplate.h \
    ../../Testjig/PTMuxTestjig/muxjig.h \
    ../../Testjig/RAMData/IRAMWidget.h \
    ../../Testjig/RAMData/PTLibraryInterfaces.h \
    ../../Testjig/RAMData/RAMTestJigInterface.h \
    ../../Testjig/RAMData/widget.h \
    ../../Testjig/VI/IVIWidget.h \
    ../../Testjig/VI/InterfacePTLibrary.h \
    ../../Testjig/VI/VITestJigInterface.h \
    ../../Testjig/VI/WaveformTestjigInterface.h \
    ../../Testjig/VI/vijig.h \
    ../../Testjig/ADCHighSpeed/AppdeviceRegisterDetails.h \
    ../../Testjig/ADCHighSpeed/ApplicationCardInterface.h \
    ../../Testjig/ADCHighSpeed/InterfaceFunctionalComponents.h \
    ../../Testjig/ADCHighSpeed/adchighspeed.h \
    ../../Testjig/ADCHighSpeed/appcardcomponents.h \
    ../../Testjig/ADCHighSpeed/appcardfunctiontemplate.h \
    ../../Testjig/ADCHighSpeed/isla118p50component.h \
    ../../Testjig/AD5318/AD5318TestJigInterface.h \
    ../../Testjig/AD5318/AppdeviceRegisterDetails.h \
    ../../Testjig/AD5318/ApplicationCardInterface.h \
    ../../Testjig/AD5318/BackPlaneInterface.h \
    ../../Testjig/AD5318/IAD5318Widget.h \
    ../../Testjig/AD5318/ICALIBTestJigInterface.h \
    ../../Testjig/AD5318/InterfaceFunctionalComponents.h \
    ../../Testjig/AD5318/PTLMH6518Interface.h \
    ../../Testjig/AD5318/PTLibraryInterfaces.h \
    ../../Testjig/AD5318/RXCALIBTestJigInterface.h \
    ../../Testjig/AD5318/RefCALIBTestJigInterface.h \
    ../../Testjig/AD5318/VCALIBTestJigInterface.h \
    ../../Testjig/AD5318/ad5293.h \
    ../../Testjig/AD5318/ad5318.h \
    ../../Testjig/AD5318/ad5318components.h \
    ../../Testjig/AD5318/ad7190component.h \
    ../../Testjig/AD5318/appcardcomponents.h \
    ../../Testjig/AD5318/appcardfunctiontemplate.h \
    ../../Testjig/PTAppBckPsoc/AppdeviceRegisterDetails.h \
    ../../Testjig/PTAppBckPsoc/ApplicationCardInterface.h \
    ../../Testjig/PTAppBckPsoc/BackPlaneInterface.h \
    ../../Testjig/PTAppBckPsoc/GPIOInterfaces.h \
    ../../Testjig/PTAppBckPsoc/IPSOCCommunication.h \
    ../../Testjig/PTAppBckPsoc/IPTAppBckPsocWidget.h \
    ../../Testjig/PTAppBckPsoc/InterfacePTLibrary.h \
    ../../Testjig/PTAppBckPsoc/PTAppBckPsocInterface.h \
    ../../Testjig/PTAppBckPsoc/PTEventInterfaces.h \
    ../../Testjig/PTAppBckPsoc/PTGPIOEventInterfaces.h \
    ../../Testjig/PTAppBckPsoc/appcardcomponents.h \
    ../../Testjig/PTAppBckPsoc/appcardfunctiontemplate.h \
    ../../Testjig/PTAppBckPsoc/headers.h \
    ../../Testjig/PTAppBckPsoc/macros.h \
    ../../Testjig/PTAppBckPsoc/ptpsoctestjiginterface.h \
    ../../DMM/Keithley2100Lib/Keithley2100Interface.h \
    ../../DMM/Keithley2100Lib/KeithleyMacros.h \
    ../../DMM/Keithley2100Lib/keithley2100lib.h \
    ../../BackPlaneInterface/BackPlaneInterface.h \
    ../../BackPlaneInterface/emidevice.h \
    ../../BackPlaneInterface/ibackplane.h \
    ../../PTApplicationcardInterface/AppdeviceRegisterDetails.h \
    ../../PTApplicationcardInterface/ApplicationCardInterface.h \
    ../../PTApplicationcardInterface/appcardfunctiontemplate.h \
    ../../PTApplicationcardInterface/ptapplicationcardplugin.h \
    ../../SPIMemoryInterface/AppdeviceRegisterDetails.h \
    ../../SPIMemoryInterface/ApplicationCardInterface.h \
    ../../SPIMemoryInterface/BackPlaneInterface.h \
    ../../SPIMemoryInterface/PTSPIMemoryInterface.h \
    ../../SPIMemoryInterface/appcardfunctiontemplate.h \
    ../../SPIMemoryInterface/macros.h \
    ../../SPIMemoryInterface/spimemoryinterface.h \
    ../../PTPsocInterface2/AppdeviceRegisterDetails.h \
    ../../PTPsocInterface2/ApplicationCardInterface.h \
    ../../PTPsocInterface2/IPSOCCommunication.h \
    ../../PTPsocInterface2/appcardfunctiontemplate.h \
    ../../PTPsocInterface2/ptpsocinterface2.h \
    ../../PTPsocInterface2/serialdevice.h \
    ../../PTPsocInterface2/src/qextserialenumerator.h \
    ../../PTPsocInterface2/src/qextserialenumerator_p.h \
    ../../PTPsocInterface2/src/qextserialport.h \
    ../../PTPsocInterface2/src/qextserialport_global.h \
    ../../PTPsocInterface2/src/qextserialport_p.h \
    ../../PTComponentsInterface/IPTComponentsInterfaces.h \
    ../../PTComponentsInterface/PTInterfaceHeaders.h \
    ../../PTComponentsInterface/ptcomponentsinterface.h \
    ../../QmaxPTInterface/InterfacePTLibrary.h \
    ../../QmaxPTInterface/PTLibraryInterfaces.h \
    ../../QmaxPTInterface/QmaxPTLibrary_global.h \
    ../../QmaxPTInterface/colors.h \
    ../../QmaxPTInterface/displayinfo.h \
    ../../QmaxPTInterface/myLineEdit.h \
    ../../QmaxPTInterface/myinputpanel.h \
    ../../QmaxPTInterface/numberpanel.h \
    ../../QmaxPTInterface/qmaxbutton.h \
    ../../QmaxPTInterface/qmaxmessagebox.h \
    ../../QmaxPTInterface/qmaxptinterface.h \
    ../../QmaxPTInterface/qmaxptlibrary.h \
    ../../QmaxPTInterface/widget.h \
    ../../PTGPIOPinInterface/GPIOInterfaces.h \
    ../../PTGPIOPinInterface/gpio.h \
    ../../PTGPIOPinInterface/ptgpiopininterface.h \
    ../../GPIOEventInterface/AppdeviceRegisterDetails.h \
    ../../GPIOEventInterface/ApplicationCardInterface.h \
    ../../GPIOEventInterface/BackPlaneInterface.h \
    ../../GPIOEventInterface/IPSOCCommunication.h \
    ../../GPIOEventInterface/PTGPIOEventInterfaces.h \
    ../../GPIOEventInterface/PTSPIMemoryInterface.h \
    ../../GPIOEventInterface/appcardcomponents.h \
    ../../GPIOEventInterface/appcardfunctiontemplate.h \
    ../../GPIOEventInterface/gpioeventinterface.h \
    ../../PTKeyEventInterfaces/KeyObject.h \
    ../../PTKeyEventInterfaces/PTEventInterfaces.h \
    ../../PTKeyEventInterfaces/PtKeyEventInterface.h \
    ../../PTKeyEventInterfaces/PtKeys.h \
    ../../PTSplashInterface/PTSplashScreen.h \
    ../../PTSplashInterface/interfacewrapper.h \
    ../../PTSplashInterface/ptsplashinterface.h \
    ../../Keithley2100Lib/Keithley2100Interface.h \
    ../../Keithley2100Lib/KeithleyMacros.h \
    ../../Keithley2100Lib/keithley2100lib.h \
    ../../PTDMMLibInterface/AppdeviceRegisterDetails.h \
    ../../PTDMMLibInterface/ApplicationCardInterface.h \
    ../../PTDMMLibInterface/BackPlaneInterface.h \
    ../../PTDMMLibInterface/CalibrationInterfaces.h \
    ../../PTDMMLibInterface/DMMLibInterface.h \
    ../../PTDMMLibInterface/IPSOCCommunication.h \
    ../../PTDMMLibInterface/InterfaceFunctionalComponents.h \
    ../../PTDMMLibInterface/ad5318components.h \
    ../../PTDMMLibInterface/ad7190component.h \
    ../../PTDMMLibInterface/appcardcomponents.h \
    ../../PTDMMLibInterface/appcardfunctiontemplate.h \
    ../../PTDMMLibInterface/macro.h \
    ../../PTDMMLibInterface/ptdmmlibinterface.h \
    ../../PTDMMLibInterface/serialdevice.h \
    ../../DMM/HY3131DMMLib/AppdeviceRegisterDetails.h \
    ../../DMM/HY3131DMMLib/ApplicationCardInterface.h \
    ../../DMM/HY3131DMMLib/BackPlaneInterface.h \
    ../../DMM/HY3131DMMLib/HY3131DMMLibInterface.h \
    ../../DMM/HY3131DMMLib/HY3131Macro.h \
    ../../DMM/HY3131DMMLib/InterfaceFunctionalComponents.h \
    ../../DMM/HY3131DMMLib/appcardcomponents.h \
    ../../DMM/HY3131DMMLib/appcardfunctiontemplate.h \
    ../../DMM/HY3131DMMLib/hy3131dmmlib.h \
    ../../Calibration/OpenShortCalib/AppdeviceRegisterDetails.h \
    ../../Calibration/OpenShortCalib/ApplicationCardInterface.h \
    ../../Calibration/OpenShortCalib/BackPlaneInterface.h \
    ../../Calibration/OpenShortCalib/InterfaceFunctionalComponents.h \
    ../../Calibration/OpenShortCalib/ad5293.h \
    ../../Calibration/OpenShortCalib/ad5318components.h \
    ../../Calibration/OpenShortCalib/ad7190component.h \
    ../../Calibration/OpenShortCalib/appcardcomponents.h \
    ../../Calibration/OpenShortCalib/appcardfunctiontemplate.h \
    ../../Calibration/OpenShortCalib/hardwareinterface.h \
    ../../Calibration/OpenShortCalib/openshortcalib.h \
    ../../Calibration/RXCalibration/AppdeviceRegisterDetails.h \
    ../../Calibration/RXCalibration/ApplicationCardInterface.h \
    ../../Calibration/RXCalibration/IRXCALIBWidget.h \
    ../../Calibration/RXCalibration/InterfaceFunctionalComponents.h \
    ../../Calibration/RXCalibration/PTLibraryInterfaces.h \
    ../../Calibration/RXCalibration/RXCALIBTestJigInterface.h \
    ../../Calibration/RXCalibration/ad5293.h \
    ../../Calibration/RXCalibration/ad5318components.h \
    ../../Calibration/RXCalibration/ad7190component.h \
    ../../Calibration/RXCalibration/adccalibration.h \
    ../../Calibration/RXCalibration/appcardcomponents.h \
    ../../Calibration/RXCalibration/appcardfunctiontemplate.h \
    ../../SPIController/AD5260.h \
    ../../SPIController/AD5293.h \
    ../../SPIController/AD5318.h \
    ../../SPIController/ApplicationCardInterface.h \
    ../../SPIController/DAC8563.h \
    ../../SPIController/DSOPSOC.h \
    ../../SPIController/ISLA118P50.h \
    ../../SPIController/InterfaceFunctionalComponents.h \
    ../../SPIController/LMH6518.h \
    ../../SPIController/Macros.h \
    ../../SPIController/SPIInterface.h \
    ../../SPIController/appcardcomponents.h \
    ../../SPIController/appcardfunctiontemplate.h \
    ../../SPIController/spicontroller.h \
    ../test_Buzzer/BackPlaneInterface.h \
    ../test_Buzzer/mainwindow.h \
    ../testSPI/AppdeviceRegisterDetails.h \
    ../testSPI/ApplicationCardInterface.h \
    ../testSPI/BackPlaneInterface.h \
    ../testSPI/DMMSPITestJigInterface.h \
    ../testSPI/DMMSPIWidget.h \
    ../testSPI/HY3131DMMLibInterface.h \
    ../testSPI/HY3131Macro.h \
    ../testSPI/InterfaceFunctionalComponents.h \
    ../testSPI/InterfacePTLibrary.h \
    ../testSPI/appcardcomponents.h \
    ../testSPI/appcardfunctiontemplate.h \
    ../testSPI/display.h \
    ../testSPI/hy3131calibration.h \
    ../testSPI/testspi.h \
    ../testKeithley2100Lib/Keithley2100Interface.h \
    ../testKeithley2100Lib/testkeithley2100lib.h \
    ../test_Encoder_SPI/BackPlaneInterface.h \
    ../test_Encoder_SPI/PTGPIOEventInterfaces.h \
    ../test_Encoder_SPI/PTLibraryInterfaces.h \
    ../test_Encoder_SPI/testencoder.h \
    ../TestMuxStatus/IPSOCCommunication.h \
    ../TestMuxStatus/mainwindow.h \
    ../../Calibration/VCalibration/AppdeviceRegisterDetails.h \
    ../../Calibration/VCalibration/ApplicationCardInterface.h \
    ../../Calibration/VCalibration/IVCALIBWidget.h \
    ../../Calibration/VCalibration/InterfaceFunctionalComponents.h \
    ../../Calibration/VCalibration/PTLibraryInterfaces.h \
    ../../Calibration/VCalibration/VCALIBTestJigInterface.h \
    ../../Calibration/VCalibration/ad5293.h \
    ../../Calibration/VCalibration/ad5318components.h \
    ../../Calibration/VCalibration/appcardcomponents.h \
    ../../Calibration/VCalibration/appcardfunctiontemplate.h \
    ../../Calibration/VCalibration/daccalibration.h \
    ../../Calibration/VICalibration/AppdeviceRegisterDetails.h \
    ../../Calibration/VICalibration/ApplicationCardInterface.h \
    ../../Calibration/VICalibration/IVCALIBWidget.h \
    ../../Calibration/VICalibration/InterfaceFunctionalComponents.h \
    ../../Calibration/VICalibration/PTLibraryInterfaces.h \
    ../../Calibration/VICalibration/VCALIBTestJigInterface.h \
    ../../Calibration/VICalibration/ad5293.h \
    ../../Calibration/VICalibration/ad5318components.h \
    ../../Calibration/VICalibration/appcardcomponents.h \
    ../../Calibration/VICalibration/appcardfunctiontemplate.h \
    ../../Calibration/VICalibration/daccalibration.h \
    ../testADCHighSpeed/mainwindow.h \
    ../testHY3131CalibInterface/HY3131Calib.h \
    ../testHY3131CalibInterface/HY3131DMMLibInterface.h \
    ../testHY3131CalibInterface/mainwindow.h \
    ../test_calibReportInterface/CalibReportInterface.h \
    ../test_calibReportInterface/test_calibreportinterface.h \
    ../test_HY3131DMMLib/HY3131DMMLibInterface.h \
    ../test_HY3131DMMLib/PTLibraryInterfaces.h \
    ../test_HY3131DMMLib/display.h \
    ../test_HY3131DMMLib/mainwindow.h \
    IPSOCCommunication.h \
    testpsocinterface2.h \
    IPSOCCommunication.h \
    testpsocinterface2.h
FORMS += ../../PortableTester/portabletester.ui \
    ../../PortableTester/probestatus.ui \
    ../../VINew/autocurvefittraces.ui \
    ../../VINew/clipdialog.ui \
    ../../VINew/embeddedkeys.ui \
    ../../VINew/mainwindow.ui \
    ../../VINew/multipletraces.ui \
    ../../VINew/mutlipewavedialog.ui \
    ../../VINew/selectprobe.ui \
    ../../VINew/visettings.ui \
    ../../FGNew/fg.ui \
    ../../SLControl/offset.ui \
    ../../SLControl/shortlocater.ui \
    ../../ICMUIInterface/daccalibration.ui \
    ../../ICMUIInterface/icm.ui \
    ../../ICMUIInterface/settings.ui \
    ../../Calibration/HY3131CalibInterface/hy3131calibration.ui \
    ../../Calibration/ReferenceCalibration/daccalibration.ui \
    ../../Calibration/GCalibration/daccalibration.ui \
    ../../Calibration/ICalibration/daccalibration.ui \
    ../../DMM/DMMAccuracy/dmmaccuracy.ui \
    ../../DMM/HY3131CalibInterface/hy3131calibration.ui \
    ../../Testjig/PortableTesterTestJig2/portabletestertestjig2.ui \
    ../../Testjig/PTPSoCTestJigInterface2/ptpsoctestjiginterface2.ui \
    ../../Testjig/AD9102GUI/ad9102ui.ui \
    ../../Testjig/FLASHMEMORY/flashMemory.ui \
    ../../Testjig/FLASHMEMORY/messagewidget.ui \
    ../../Testjig/ADCHighAccuracy/adhighaccuracy.ui \
    ../../Testjig/APPCardDRVRECE/ptappcarddrvrecev.ui \
    ../../Testjig/APPCardRelayUI/ICMJig/widget.ui \
    ../../Testjig/APPCardRelayUI/mainwindow.ui \
    ../../Testjig/AWG/widget.ui \
    ../../Testjig/DDS/daccalibration.ui \
    ../../Testjig/DDS/ddswidget.ui \
    ../../Testjig/DMM/dmmjig.ui \
    ../../Testjig/ICMJig/widget.ui \
    ../../Testjig/PlotWaveForm/widget.ui \
    ../../Testjig/PtKeyKnob/ptkeyknob.ui \
    ../../Testjig/PTMuxTestjig/muxjig.ui \
    ../../Testjig/RAMData/widget.ui \
    ../../Testjig/VI/vijig.ui \
    ../../Testjig/ADCHighSpeed/adchighspeed.ui \
    ../../Testjig/AD5318/ad5318.ui \
    ../../Testjig/PTAppBckPsoc/ptpsoctestjiginterface.ui \
    ../../QmaxPTInterface/displayinfo.ui \
    ../../QmaxPTInterface/myinputpanelform.ui \
    ../../QmaxPTInterface/numberpanel.ui \
    ../../QmaxPTInterface/widget.ui \
    ../../Calibration/OpenShortCalib/openshortcalib.ui \
    ../../Calibration/RXCalibration/daccalibration.ui \
    ../test_Buzzer/mainwindow.ui \
    ../testSPI/hy3131calibration.ui \
    ../testSPI/testspi.ui \
    ../testKeithley2100Lib/testkeithley2100lib.ui \
    ../test_Encoder_SPI/testencoder.ui \
    ../TestMuxStatus/mainwindow.ui \
    ../../Calibration/VCalibration/daccalibration.ui \
    ../../Calibration/VICalibration/daccalibration.ui \
    ../testADCHighSpeed/mainwindow.ui \
    ../testHY3131CalibInterface/mainwindow.ui \
    ../test_calibReportInterface/test_calibreportinterface.ui \
    ../test_HY3131DMMLib/mainwindow.ui \
    testpsocinterface2.ui \
    testpsocinterface2.ui
RESOURCES = ../../PortableTester/PortableTester.qrc \
    ../../VINew/vi.qrc \
    ../../FGNew/fg.qrc \
    ../../SLControl/svgResource.qrc \
    ../../SLControl/svgbutton.qrc \
    ../../ICMUIInterface/fp_res.qrc \
    ../../ICMUIInterface/icm.qrc \
    ../../Calibration/HY3131CalibInterface/testSPI.qrc \
    ../../CalibReport/report.qrc \
    ../../DMM/HY3131CalibInterface/testSPI.qrc \
    ../../Testjig/PortableTesterTestJig2/pttj2.qrc \
    ../../Testjig/PTPSoCTestJigInterface2/psoctj.qrc \
    ../../Testjig/AD9102GUI/ad9102.qrc \
    ../../Testjig/FLASHMEMORY/fm.qrc \
    ../../Testjig/ADCHighAccuracy/haadc.qrc \
    ../../Testjig/APPCardDRVRECE/appdrvrx.qrc \
    ../../Testjig/APPCardRelayUI/ICMJig/icmtj.qrc \
    ../../Testjig/APPCardRelayUI/apc.qrc \
    ../../Testjig/AWG/awgtj.qrc \
    ../../Testjig/DDS/ddstj.qrc \
    ../../Testjig/DMM/dmmtj.qrc \
    ../../Testjig/ICMJig/icmtj.qrc \
    ../../Testjig/PlotWaveForm/pwf.qrc \
    ../../Testjig/PtKeyKnob/ptkeyknob.qrc \
    ../../Testjig/PTMuxTestjig/muxjig.qrc \
    ../../Testjig/RAMData/RAMData.qrc \
    ../../Testjig/VI/vitj.qrc \
    ../../Testjig/AD5318/ad5318.qrc \
    ../../Testjig/PTAppBckPsoc/psoctj.qrc \
    ../../QmaxPTInterface/qmaxptresource.qrc \
    ../../PTSplashInterface/PTSplashInterface.qrc \
    ../testSPI/testSPI.qrc
