/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <ISO_DI2.h>
#include <ISO_DI2_aliases.h>
#include <ISO_SCS.h>
#include <ISO_SCS_aliases.h>
#include <ISO_SCLK.h>
#include <ISO_SCLK_aliases.h>
#include <ISO_SDI.h>
#include <ISO_SDI_aliases.h>
#include <ISO_SDO.h>
#include <ISO_SDO_aliases.h>
#include <ISO_DI0.h>
#include <ISO_DI0_aliases.h>
#include <CS.h>
#include <CS_aliases.h>
#include <CK.h>
#include <CK_aliases.h>
#include <DIn.h>
#include <DIn_aliases.h>
#include <DOut.h>
#include <DOut_aliases.h>
#include <RL6_CTR.h>
#include <RL6_CTR_aliases.h>
#include <RL1_CTR.h>
#include <RL1_CTR_aliases.h>
#include <RL4_CTR.h>
#include <RL4_CTR_aliases.h>
#include <RL3_CTR.h>
#include <RL3_CTR_aliases.h>
#include <RL2_CTR.h>
#include <RL2_CTR_aliases.h>
#include <RL5_CTR.h>
#include <RL5_CTR_aliases.h>
#include <RL7_CTR.h>
#include <RL7_CTR_aliases.h>
#include <ISO_DI1.h>
#include <ISO_DI1_aliases.h>
#include <I2C_1.h>
#include <I2C_1_PVT.h>
#include <I2C1_SCL.h>
#include <I2C1_SCL_aliases.h>
#include <I2C1_SDA.h>
#include <I2C1_SDA_aliases.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/

