/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created: Sat Sep 6 10:53:13 2014
**      by: Qt User Interface Compiler version 4.7.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QMainWindow>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QGroupBox *groupBox;
    QPushButton *butRL1;
    QPushButton *butRL2;
    QPushButton *butRL3;
    QPushButton *butRL4;
    QPushButton *butRL5;
    QLabel *label;
    QFrame *line;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QPushButton *butRL9;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QPushButton *butRL8;
    QLabel *label_9;
    QPushButton *butRL6;
    QPushButton *butRL7;
    QGroupBox *groupBox_2;
    QPushButton *butRL23;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QPushButton *butRL22;
    QLabel *label_13;
    QPushButton *butRL10;
    QPushButton *butRL20;
    QPushButton *butRL26;
    QLabel *label_14;
    QFrame *line_2;
    QPushButton *butRL11;
    QPushButton *butRL14;
    QPushButton *butRL13;
    QLabel *label_15;
    QPushButton *butRL17;
    QLabel *label_16;
    QPushButton *butRL12;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QFrame *line_3;
    QPushButton *butRL21;
    QPushButton *butRL27;
    QPushButton *butRL25;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QPushButton *butRL15;
    QPushButton *butRL24;
    QFrame *line_4;
    QLabel *label_25;
    QPushButton *butRL18;
    QPushButton *butRL16;
    QLabel *label_26;
    QLabel *label_27;
    QPushButton *butRL19;
    QPushButton *butRLYRD;
    QFrame *line_5;
    QGroupBox *groupBox_3;
    QLabel *label_28;
    QLabel *label_29;
    QPushButton *butWrite;
    QPushButton *butREAD;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(800, 600);
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(108, 108, 109, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(162, 162, 164, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(135, 135, 136, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(54, 54, 54, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(72, 72, 72, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        QBrush brush6(QColor(0, 0, 0, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush4);
        QBrush brush7(QColor(255, 255, 220, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        MainWindow->setPalette(palette);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        groupBox = new QGroupBox(centralWidget);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(40, 20, 381, 181));
        butRL1 = new QPushButton(groupBox);
        butRL1->setObjectName(QString::fromUtf8("butRL1"));
        butRL1->setGeometry(QRect(50, 43, 51, 51));
        butRL1->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);\n"
"color: rgb(85, 255, 255);"));
        butRL1->setCheckable(false);
        butRL1->setFlat(false);
        butRL2 = new QPushButton(groupBox);
        butRL2->setObjectName(QString::fromUtf8("butRL2"));
        butRL2->setGeometry(QRect(112, 43, 51, 51));
        butRL2->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        butRL3 = new QPushButton(groupBox);
        butRL3->setObjectName(QString::fromUtf8("butRL3"));
        butRL3->setGeometry(QRect(170, 43, 51, 51));
        butRL3->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        butRL4 = new QPushButton(groupBox);
        butRL4->setObjectName(QString::fromUtf8("butRL4"));
        butRL4->setGeometry(QRect(230, 43, 51, 51));
        butRL4->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        butRL5 = new QPushButton(groupBox);
        butRL5->setObjectName(QString::fromUtf8("butRL5"));
        butRL5->setGeometry(QRect(290, 43, 51, 51));
        butRL5->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        label = new QLabel(groupBox);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(60, 25, 31, 20));
        line = new QFrame(groupBox);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(0, 92, 381, 16));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        label_2 = new QLabel(groupBox);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(120, 26, 31, 20));
        label_3 = new QLabel(groupBox);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(180, 26, 31, 20));
        label_4 = new QLabel(groupBox);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(240, 26, 31, 20));
        label_5 = new QLabel(groupBox);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(300, 26, 31, 20));
        butRL9 = new QPushButton(groupBox);
        butRL9->setObjectName(QString::fromUtf8("butRL9"));
        butRL9->setGeometry(QRect(228, 120, 51, 51));
        QPalette palette1;
        QBrush brush8(QColor(170, 0, 0, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush8);
        QBrush brush9(QColor(85, 255, 255, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        QBrush brush10(QColor(126, 125, 124, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        butRL9->setPalette(palette1);
        QFont font;
        font.setPointSize(12);
        font.setBold(true);
        font.setWeight(75);
        butRL9->setFont(font);
        butRL9->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        label_6 = new QLabel(groupBox);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(238, 103, 31, 20));
        label_7 = new QLabel(groupBox);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(58, 102, 31, 20));
        label_8 = new QLabel(groupBox);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(118, 103, 31, 20));
        butRL8 = new QPushButton(groupBox);
        butRL8->setObjectName(QString::fromUtf8("butRL8"));
        butRL8->setGeometry(QRect(168, 120, 51, 51));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        butRL8->setPalette(palette2);
        butRL8->setFont(font);
        butRL8->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        label_9 = new QLabel(groupBox);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(178, 103, 31, 20));
        butRL6 = new QPushButton(groupBox);
        butRL6->setObjectName(QString::fromUtf8("butRL6"));
        butRL6->setGeometry(QRect(48, 120, 51, 51));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        butRL6->setPalette(palette3);
        butRL6->setFont(font);
        butRL6->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        butRL7 = new QPushButton(groupBox);
        butRL7->setObjectName(QString::fromUtf8("butRL7"));
        butRL7->setGeometry(QRect(110, 120, 51, 51));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        butRL7->setPalette(palette4);
        butRL7->setFont(font);
        butRL7->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        groupBox_2 = new QGroupBox(centralWidget);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(40, 200, 381, 361));
        groupBox_2->setStyleSheet(QString::fromUtf8(""));
        butRL23 = new QPushButton(groupBox_2);
        butRL23->setObjectName(QString::fromUtf8("butRL23"));
        butRL23->setGeometry(QRect(230, 50, 51, 51));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        butRL23->setPalette(palette5);
        butRL23->setFont(font);
        butRL23->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        label_10 = new QLabel(groupBox_2);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(240, 33, 41, 20));
        label_11 = new QLabel(groupBox_2);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(53, 32, 41, 20));
        label_12 = new QLabel(groupBox_2);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(120, 33, 41, 20));
        butRL22 = new QPushButton(groupBox_2);
        butRL22->setObjectName(QString::fromUtf8("butRL22"));
        butRL22->setGeometry(QRect(170, 50, 51, 51));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        butRL22->setPalette(palette6);
        butRL22->setFont(font);
        butRL22->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        label_13 = new QLabel(groupBox_2);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(180, 33, 41, 20));
        butRL10 = new QPushButton(groupBox_2);
        butRL10->setObjectName(QString::fromUtf8("butRL10"));
        butRL10->setGeometry(QRect(50, 50, 51, 51));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        butRL10->setPalette(palette7);
        butRL10->setFont(font);
        butRL10->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        butRL20 = new QPushButton(groupBox_2);
        butRL20->setObjectName(QString::fromUtf8("butRL20"));
        butRL20->setGeometry(QRect(112, 50, 51, 51));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette8.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        butRL20->setPalette(palette8);
        butRL20->setFont(font);
        butRL20->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        butRL26 = new QPushButton(groupBox_2);
        butRL26->setObjectName(QString::fromUtf8("butRL26"));
        butRL26->setGeometry(QRect(290, 50, 51, 51));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette9.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        butRL26->setPalette(palette9);
        butRL26->setFont(font);
        butRL26->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        label_14 = new QLabel(groupBox_2);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(300, 33, 41, 20));
        line_2 = new QFrame(groupBox_2);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(0, 102, 381, 16));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        butRL11 = new QPushButton(groupBox_2);
        butRL11->setObjectName(QString::fromUtf8("butRL11"));
        butRL11->setGeometry(QRect(50, 137, 51, 51));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette10.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette10.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette10.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette10.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette10.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette10.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette10.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette10.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette10.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        butRL11->setPalette(palette10);
        butRL11->setFont(font);
        butRL11->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        butRL14 = new QPushButton(groupBox_2);
        butRL14->setObjectName(QString::fromUtf8("butRL14"));
        butRL14->setGeometry(QRect(230, 137, 51, 51));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette11.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette11.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette11.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette11.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette11.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette11.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette11.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette11.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette11.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette11.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette11.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        butRL14->setPalette(palette11);
        butRL14->setFont(font);
        butRL14->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        butRL13 = new QPushButton(groupBox_2);
        butRL13->setObjectName(QString::fromUtf8("butRL13"));
        butRL13->setGeometry(QRect(170, 137, 51, 51));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette12.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette12.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette12.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette12.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette12.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette12.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette12.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette12.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette12.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette12.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette12.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        butRL13->setPalette(palette12);
        butRL13->setFont(font);
        butRL13->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        label_15 = new QLabel(groupBox_2);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(180, 120, 41, 20));
        butRL17 = new QPushButton(groupBox_2);
        butRL17->setObjectName(QString::fromUtf8("butRL17"));
        butRL17->setGeometry(QRect(290, 137, 51, 51));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette13.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette13.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette13.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette13.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette13.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette13.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette13.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette13.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette13.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette13.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette13.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        butRL17->setPalette(palette13);
        butRL17->setFont(font);
        butRL17->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        label_16 = new QLabel(groupBox_2);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(300, 120, 41, 20));
        butRL12 = new QPushButton(groupBox_2);
        butRL12->setObjectName(QString::fromUtf8("butRL12"));
        butRL12->setGeometry(QRect(112, 137, 51, 51));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette14.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette14.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette14.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette14.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette14.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette14.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette14.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette14.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette14.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette14.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette14.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        butRL12->setPalette(palette14);
        butRL12->setFont(font);
        butRL12->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        label_17 = new QLabel(groupBox_2);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(240, 120, 41, 20));
        label_18 = new QLabel(groupBox_2);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(53, 119, 41, 20));
        label_19 = new QLabel(groupBox_2);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(120, 120, 41, 20));
        line_3 = new QFrame(groupBox_2);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setGeometry(QRect(0, 192, 381, 16));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        butRL21 = new QPushButton(groupBox_2);
        butRL21->setObjectName(QString::fromUtf8("butRL21"));
        butRL21->setGeometry(QRect(48, 220, 51, 51));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette15.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette15.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette15.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette15.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette15.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette15.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette15.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette15.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette15.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette15.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette15.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        butRL21->setPalette(palette15);
        butRL21->setFont(font);
        butRL21->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        butRL27 = new QPushButton(groupBox_2);
        butRL27->setObjectName(QString::fromUtf8("butRL27"));
        butRL27->setGeometry(QRect(228, 220, 51, 51));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette16.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette16.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette16.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette16.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette16.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette16.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette16.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette16.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette16.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette16.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette16.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        butRL27->setPalette(palette16);
        butRL27->setFont(font);
        butRL27->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        butRL25 = new QPushButton(groupBox_2);
        butRL25->setObjectName(QString::fromUtf8("butRL25"));
        butRL25->setGeometry(QRect(168, 220, 51, 51));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette17.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette17.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette17.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette17.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette17.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette17.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette17.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette17.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette17.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette17.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette17.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        butRL25->setPalette(palette17);
        butRL25->setFont(font);
        butRL25->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        label_20 = new QLabel(groupBox_2);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(178, 203, 41, 20));
        label_21 = new QLabel(groupBox_2);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(51, 202, 41, 20));
        label_22 = new QLabel(groupBox_2);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(298, 203, 41, 20));
        label_23 = new QLabel(groupBox_2);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(238, 203, 41, 20));
        label_24 = new QLabel(groupBox_2);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(118, 203, 41, 20));
        butRL15 = new QPushButton(groupBox_2);
        butRL15->setObjectName(QString::fromUtf8("butRL15"));
        butRL15->setGeometry(QRect(288, 220, 51, 51));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette18.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette18.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette18.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette18.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette18.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette18.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette18.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette18.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette18.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette18.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette18.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        butRL15->setPalette(palette18);
        butRL15->setFont(font);
        butRL15->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        butRL24 = new QPushButton(groupBox_2);
        butRL24->setObjectName(QString::fromUtf8("butRL24"));
        butRL24->setGeometry(QRect(110, 220, 51, 51));
        QPalette palette19;
        palette19.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette19.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette19.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette19.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette19.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette19.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette19.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette19.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette19.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette19.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette19.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette19.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        butRL24->setPalette(palette19);
        butRL24->setFont(font);
        butRL24->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        line_4 = new QFrame(groupBox_2);
        line_4->setObjectName(QString::fromUtf8("line_4"));
        line_4->setGeometry(QRect(0, 273, 381, 16));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        label_25 = new QLabel(groupBox_2);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(120, 283, 41, 20));
        butRL18 = new QPushButton(groupBox_2);
        butRL18->setObjectName(QString::fromUtf8("butRL18"));
        butRL18->setGeometry(QRect(112, 300, 51, 51));
        QPalette palette20;
        palette20.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette20.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette20.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette20.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette20.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette20.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette20.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette20.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette20.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette20.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette20.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette20.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        butRL18->setPalette(palette20);
        butRL18->setFont(font);
        butRL18->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        butRL16 = new QPushButton(groupBox_2);
        butRL16->setObjectName(QString::fromUtf8("butRL16"));
        butRL16->setGeometry(QRect(50, 300, 51, 51));
        QPalette palette21;
        palette21.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette21.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette21.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette21.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette21.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette21.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette21.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette21.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette21.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette21.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette21.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette21.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        butRL16->setPalette(palette21);
        butRL16->setFont(font);
        butRL16->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        label_26 = new QLabel(groupBox_2);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(180, 283, 41, 20));
        label_27 = new QLabel(groupBox_2);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(53, 282, 41, 20));
        butRL19 = new QPushButton(groupBox_2);
        butRL19->setObjectName(QString::fromUtf8("butRL19"));
        butRL19->setGeometry(QRect(170, 300, 51, 51));
        QPalette palette22;
        palette22.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette22.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette22.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette22.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette22.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette22.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette22.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette22.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette22.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette22.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette22.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette22.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        butRL19->setPalette(palette22);
        butRL19->setFont(font);
        butRL19->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 0, 0);"));
        butRLYRD = new QPushButton(groupBox_2);
        butRLYRD->setObjectName(QString::fromUtf8("butRLYRD"));
        butRLYRD->setGeometry(QRect(270, 292, 93, 51));
        line_5 = new QFrame(groupBox_2);
        line_5->setObjectName(QString::fromUtf8("line_5"));
        line_5->setGeometry(QRect(240, 280, 20, 81));
        line_5->setFrameShape(QFrame::VLine);
        line_5->setFrameShadow(QFrame::Sunken);
        groupBox_3 = new QGroupBox(centralWidget);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(430, 20, 291, 201));
        label_28 = new QLabel(groupBox_3);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(30, 30, 91, 41));
        label_29 = new QLabel(groupBox_3);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(30, 90, 91, 41));
        butWrite = new QPushButton(groupBox_3);
        butWrite->setObjectName(QString::fromUtf8("butWrite"));
        butWrite->setGeometry(QRect(160, 140, 93, 51));
        label_28->raise();
        label_29->raise();
        butWrite->raise();
        butREAD = new QPushButton(centralWidget);
        butREAD->setObjectName(QString::fromUtf8("butREAD"));
        butREAD->setGeometry(QRect(470, 160, 93, 51));
        MainWindow->setCentralWidget(centralWidget);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0, QApplication::UnicodeUTF8));
        groupBox->setTitle(QApplication::translate("MainWindow", "Drive Relay Status", 0, QApplication::UnicodeUTF8));
        butRL1->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        butRL2->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        butRL3->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        butRL4->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        butRL5->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("MainWindow", "RL1", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("MainWindow", "RL2", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("MainWindow", "RL3", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("MainWindow", "RL4", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("MainWindow", "RL5", 0, QApplication::UnicodeUTF8));
        butRL9->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("MainWindow", "RL9", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("MainWindow", "RL6", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("MainWindow", "RL7", 0, QApplication::UnicodeUTF8));
        butRL8->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("MainWindow", "RL8", 0, QApplication::UnicodeUTF8));
        butRL6->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        butRL7->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        groupBox_2->setTitle(QApplication::translate("MainWindow", "Receive Relay Status", 0, QApplication::UnicodeUTF8));
        butRL23->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("MainWindow", "RL23", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("MainWindow", "RL10", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("MainWindow", "RL20", 0, QApplication::UnicodeUTF8));
        butRL22->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("MainWindow", "RL22", 0, QApplication::UnicodeUTF8));
        butRL10->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        butRL20->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        butRL26->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("MainWindow", "RL26", 0, QApplication::UnicodeUTF8));
        butRL11->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        butRL14->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        butRL13->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("MainWindow", "RL13", 0, QApplication::UnicodeUTF8));
        butRL17->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("MainWindow", "RL17", 0, QApplication::UnicodeUTF8));
        butRL12->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("MainWindow", "RL14", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("MainWindow", "RL11", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("MainWindow", "RL12", 0, QApplication::UnicodeUTF8));
        butRL21->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        butRL27->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        butRL25->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("MainWindow", "RL25", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("MainWindow", "RL21", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("MainWindow", "RL15", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("MainWindow", "RL27", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("MainWindow", "RL24", 0, QApplication::UnicodeUTF8));
        butRL15->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        butRL24->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("MainWindow", "RL18", 0, QApplication::UnicodeUTF8));
        butRL18->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        butRL16->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("MainWindow", "RL19", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("MainWindow", "RL16", 0, QApplication::UnicodeUTF8));
        butRL19->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        butRLYRD->setText(QApplication::translate("MainWindow", "RLY READ", 0, QApplication::UnicodeUTF8));
        groupBox_3->setTitle(QApplication::translate("MainWindow", "General", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("MainWindow", "ADDRESS :", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("MainWindow", "DATA:", 0, QApplication::UnicodeUTF8));
        butWrite->setText(QApplication::translate("MainWindow", "WRITE", 0, QApplication::UnicodeUTF8));
        butREAD->setText(QApplication::translate("MainWindow", "READ", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
