/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.0 Component Pack 3
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <Clock.h>
#include <RTX51.h>
#include <Clk_PWM.h>
#include <PWM_Out.h>
#include <PWM_Out_aliases.h>
#include <PWM.h>
#include <k_isr.h>
#include <KEY.h>
#include <KEY_aliases.h>
#include <ICM_SEL.h>
#include <ICM_SEL_aliases.h>
#include <I_SEL.h>
#include <I_SEL_aliases.h>
#include <MUXSEL_A.h>
#include <MUXSEL_A_aliases.h>
#include <MUXSEL_B.h>
#include <MUXSEL_B_aliases.h>
#include <VI2_SEL.h>
#include <VI2_SEL_aliases.h>
#include <SCOPE2_SEL.h>
#include <SCOPE2_SEL_aliases.h>
#include <SCOPE1_SEL.h>
#include <SCOPE1_SEL_aliases.h>
#include <FG1_SEL.h>
#include <FG1_SEL_aliases.h>
#include <VI1_SEL.h>
#include <VI1_SEL_aliases.h>
#include <RR1_100V.h>
#include <RR1_100V_aliases.h>
#include <LV_SEL.h>
#include <LV_SEL_aliases.h>
#include <TRIGIN_PSoC.h>
#include <TRIGIN_PSoC_aliases.h>
#include <I10mA_SEL.h>
#include <I10mA_SEL_aliases.h>
#include <I100mA_SEL.h>
#include <I100mA_SEL_aliases.h>
#include <I10A_SEL.h>
#include <I10A_SEL_aliases.h>
#include <RES_SEL1.h>
#include <RES_SEL1_aliases.h>
#include <RES_SEL0.h>
#include <RES_SEL0_aliases.h>
#include <RR2_0V.h>
#include <RR2_0V_aliases.h>
#include <RR2_1V.h>
#include <RR2_1V_aliases.h>
#include <RR2_10V.h>
#include <RR2_10V_aliases.h>
#include <RR2_100V.h>
#include <RR2_100V_aliases.h>
#include <DIV_SEL2.h>
#include <DIV_SEL2_aliases.h>
#include <RR1_0V.h>
#include <RR1_0V_aliases.h>
#include <RR1_1V.h>
#include <RR1_1V_aliases.h>
#include <RR1_10V.h>
#include <RR1_10V_aliases.h>
#include <DMM_SEL.h>
#include <DMM_SEL_aliases.h>
#include <DMM_2WSEL.h>
#include <DMM_2WSEL_aliases.h>
#include <G10M_SEL.h>
#include <G10M_SEL_aliases.h>
#include <K1_SENSE.h>
#include <K1_SENSE_aliases.h>
#include <K2_SENSE.h>
#include <K2_SENSE_aliases.h>
#include <MOSI.h>
#include <MOSI_aliases.h>
#include <MISO.h>
#include <MISO_aliases.h>
#include <PSoC_INT0.h>
#include <PSoC_INT0_aliases.h>
#include <Key1.h>
#include <Key1_aliases.h>
#include <Key2.h>
#include <Key2_aliases.h>
#include <PSoC_INT1.h>
#include <PSoC_INT1_aliases.h>
#include <SPIM.h>
#include <SCK.h>
#include <SCK_aliases.h>
#include <CSN.h>
#include <CSN_aliases.h>
#include <isr.h>
#include <S1_100V.h>
#include <S1_100V_aliases.h>
#include <UART.h>
#include <U_CLOCK.h>
#include <SPIM_IntClock.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/
