#ifndef QMAXPTLIBRARY_GLOBAL_H
#define QMAXPTLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QMAXPTLIBRARY_LIBRARY)
#  define QMAXPTLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QMAXPTLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QMAXPTLIBRARY_GLOBAL_H
