/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <BCH1_DIV0_RLY.h>
#include <BCH1_DIV0_RLY_aliases.h>
#include <BCH1_DIV1_RLY.h>
#include <BCH1_DIV1_RLY_aliases.h>
#include <BCH1_CALIB_RLY.h>
#include <BCH1_CALIB_RLY_aliases.h>
#include <BCH2_DIV0_RLY.h>
#include <BCH2_DIV0_RLY_aliases.h>
#include <BCH2_DIV1_RLY.h>
#include <BCH2_DIV1_RLY_aliases.h>
#include <BCH2_CALIB_RLY.h>
#include <BCH2_CALIB_RLY_aliases.h>
#include <BTRG_EXT5_RLY.h>
#include <BTRG_EXT5_RLY_aliases.h>
#include <SAMPLEMODE_S0.h>
#include <SAMPLEMODE_S0_aliases.h>
#include <SAMPLEMODE_S1.h>
#include <SAMPLEMODE_S1_aliases.h>
#include <CH1_CUPSEL0_RLY.h>
#include <CH1_CUPSEL0_RLY_aliases.h>
#include <CH1_CUPSEL1_RLY.h>
#include <CH1_CUPSEL1_RLY_aliases.h>
#include <CH2_CUPSEL0_RLY.h>
#include <CH2_CUPSEL0_RLY_aliases.h>
#include <CH2_CUPSEL1_RLY.h>
#include <CH2_CUPSEL1_RLY_aliases.h>
#include <ATTN_SEL0.h>
#include <ATTN_SEL0_aliases.h>
#include <ATTN_SEL1.h>
#include <ATTN_SEL1_aliases.h>
#include <ATTN_SEL2.h>
#include <ATTN_SEL2_aliases.h>
#include <ATTN_SEL3.h>
#include <ATTN_SEL3_aliases.h>
#include <FILTER_SEL.h>
#include <FILTER_SEL_aliases.h>
#include <TRIG_HSYS_SEL0.h>
#include <TRIG_HSYS_SEL0_aliases.h>
#include <TRIG_HSYS_SEL1.h>
#include <TRIG_HSYS_SEL1_aliases.h>
#include <PSOC_SPI_CS.h>
#include <PSOC_SPI_CS_aliases.h>
#include <PSOC_SPI_CLK.h>
#include <PSOC_SPI_CLK_aliases.h>
#include <PSOC_SPI_DI.h>
#include <PSOC_SPI_DI_aliases.h>
#include <PSOC_SPI_DO.h>
#include <PSOC_SPI_DO_aliases.h>
#include <SP6_SPI_CSSEL.h>
#include <SP6_SPI_CSSEL_aliases.h>
#include <FLASH_SPI_CS.h>
#include <FLASH_SPI_CS_aliases.h>
#include <FLASH_SPI_CK.h>
#include <FLASH_SPI_CK_aliases.h>
#include <FLASH_SPI_DI.h>
#include <FLASH_SPI_DI_aliases.h>
#include <FLASH_SPI_DO.h>
#include <FLASH_SPI_DO_aliases.h>
#include <SPIS.h>
#include <SPIS_PVT.h>
#include <SPIS_IntClock.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/

